services:
  lvfs:
    image: lvfs:latest
    environment:
      LVFS_HOST_NAME: localhost
      LVFS_CDN_DOMAIN: localhost
    secrets:
      - secret_key
      - secret_vendor_salt
      - secret_addr_salt
secrets:
  secret_key:
    file: secrets/secret_key
  secret_vendor_salt:
    file: secrets/secret_vendor_salt
  secret_addr_salt:
    file: secrets/secret_addr_salt
